Add the ability to DM user on punishment
The-Coding-Empire/discord-bot pull request #15
Opened 2023-06-21 06:07 UTC by Jeymen

I've added the ability to DM user on punishment. If the user's DM's are off, a follow-up message will be sent alerting the moderators.

2023-06-21 06:43 UTC, Pdzly commented on src/commands/ban.ts
> +          .catch(() => interaction.followUp("Can't send DM to the user!"));
I would add here from whom for auditability

2023-06-21 06:43 UTC, Pdzly commented on src/commands/ban.ts
> +        await user.send(`You have been unbanned.`)
Same here

2023-06-21 06:43 UTC, Pdzly commented on src/commands/kick.ts
> +        await user.send(`You have been kicked for ${reason}.`)
Same here

2023-06-21 06:44 UTC, Pdzly commented on src/commands/mute.ts
> +            await user.send(`You have been muted for ${time} minute(s) for ${reason}`)
Sane here

2023-06-21 18:12 UTC, Pdzly requested changes

2023-06-21 18:12 UTC, Pdzly commented on src/commands/kick.ts
> +          interaction.followUp(`Can't send DM to ${user}!`)
Same here!

2023-06-21 18:12 UTC, Pdzly commented on src/commands/mute.ts
> +            await user.send(`You have been unmuted in ${interaction.guild.name}`)
Here too

2023-06-22 11:56 UTC, Jeymen commented
This is being worked on by @Jeymen.

2023-06-22 17:49 UTC, Pdzly approved these changes
Nice work!  The only issue is still the permissions ( is the user over the other user )

2023-06-22 17:50 UTC, Jeymen commented
> Nice work! The only issue is still the permissions ( is the user over the other user )

That will be worked on in a future pull request!

2023-06-22 17:51 UTC, merged